# Generated by Django 6.0.5 on 2026-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=30)),
                ('idade', models.PositiveIntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('OUTRO', 'Prefiro não dizer')], max_length=30)),
                ('objetivo', models.CharField(choices=[('RELACIONAMENTO_SERIO', 'Relacionamento sério'), ('CONHECER_COM_INTENCAO', 'Conhecer pessoas com intenção'), ('AMIZADE_EVOLUIR', 'Amizade que pode evoluir'), ('CASAMENTO_FUTURO', 'Casamento no futuro')], max_length=40)),
                ('aceita_verificacao', models.BooleanField(default=False)),
                ('foto_perfil', models.ImageField(upload_to='pedidos/fotos/')),
                ('foto_extra_1', models.ImageField(upload_to='pedidos/fotos/')),
                ('foto_extra_2', models.ImageField(upload_to='pedidos/fotos/')),
                ('foto_extra_3', models.ImageField(upload_to='pedidos/fotos/')),
                ('bi_frente', models.ImageField(upload_to='pedidos/documentos/')),
                ('bi_verso', models.ImageField(upload_to='pedidos/documentos/')),
                ('selfie_com_bi', models.ImageField(upload_to='pedidos/documentos/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em análise'), ('PRECISA_CORRIGIR', 'Precisa corrigir'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('BLOQUEADO', 'Bloqueado')], default='PENDENTE', max_length=30)),
                ('observacao_admin', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido de entrada',
                'verbose_name_plural': 'Pedidos de entrada',
                'ordering': ['-criado_em'],
            },
        ),
    ]
