# Generated by Django 6.0.5 on 2026-05-08 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoentrada',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='QuestionarioEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidade', models.CharField(choices=[('SIM', 'Sim, estou disponível'), ('COM_CALMA', 'Quero conhecer com calma'), ('NAO_SEI', 'Ainda não tenho certeza')], max_length=30)),
                ('tem_filhos', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('PREFIRO_NAO_DIZER', 'Prefiro não dizer')], max_length=30)),
                ('aceita_pessoa_com_filhos', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('DEPENDE', 'Depende')], max_length=30)),
                ('cidade_preferida', models.CharField(help_text='Cidade ou região onde gostaria de conhecer pessoas.', max_length=120)),
                ('faixa_etaria_preferida', models.CharField(help_text='Ex: 25 a 35 anos', max_length=80)),
                ('sobre_si', models.TextField(help_text='Fale um pouco sobre si.')),
                ('o_que_valoriza', models.TextField(help_text='O que mais valoriza numa relação?')),
                ('o_que_nao_aceita', models.TextField(help_text='O que não aceita numa relação?')),
                ('aceita_regras', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionario', to='entradas.pedidoentrada')),
            ],
            options={
                'verbose_name': 'Questionário de entrada',
                'verbose_name_plural': 'Questionários de entrada',
                'ordering': ['-criado_em'],
            },
        ),
    ]
