# Generated by Django 6.0.5 on 2026-05-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_pedidoentrada_token_questionarioentrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilNKATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_publico', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=30)),
                ('objetivo', models.CharField(max_length=40)),
                ('sobre_si', models.TextField()),
                ('o_que_valoriza', models.TextField()),
                ('o_que_nao_aceita', models.TextField()),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('PAUSADO', 'Pausado'), ('BLOQUEADO', 'Bloqueado')], default='ATIVO', max_length=30)),
                ('visivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='entradas.pedidoentrada')),
            ],
            options={
                'verbose_name': 'Perfil NKATA',
                'verbose_name_plural': 'Perfis NKATA',
                'ordering': ['-criado_em'],
            },
        ),
    ]
