# Generated by Django 6.0.5 on 2026-05-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0003_perfilnkata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilnkata',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('OUTRO', 'Prefiro não dizer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='perfilnkata',
            name='objetivo',
            field=models.CharField(choices=[('RELACIONAMENTO_SERIO', 'Relacionamento sério'), ('CONHECER_COM_INTENCAO', 'Conhecer pessoas com intenção'), ('AMIZADE_EVOLUIR', 'Amizade que pode evoluir'), ('CASAMENTO_FUTURO', 'Casamento no futuro')], max_length=40),
        ),
    ]
