# Generated by Django 6.0.5 on 2026-05-08 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0004_alter_perfilnkata_genero_alter_perfilnkata_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INTERESSE', 'Tenho interesse'), ('GOSTAR', 'Gostar'), ('SEGUIR', 'Seguir')], max_length=30)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_recebidas', to='entradas.perfilnkata')),
            ],
            options={
                'verbose_name': 'Ação de perfil',
                'verbose_name_plural': 'Ações de perfil',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('perfil', 'tipo', 'session_key'), name='acao_unica_por_sessao')],
            },
        ),
    ]
