# Generated by Django 6.0.5 on 2026-05-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_acaoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilnkata',
            name='owner_session_key',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
