# Generated by Django 6.0.5 on 2026-05-09 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0006_perfilnkata_owner_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GOSTEI_DO_PERFIL', 'Olá, gostei do seu perfil e gostaria de conhecer melhor.'), ('CONVERSAR_COM_CALMA', 'Achei o seu perfil interessante. Podemos conversar com calma?'), ('ALGO_SERIO', 'Vejo que procuramos algo sério. Gostaria de saber mais sobre si.')], max_length=40)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='entradas.perfilnkata')),
            ],
            options={
                'verbose_name': 'Mensagem de perfil',
                'verbose_name_plural': 'Mensagens de perfil',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('perfil', 'tipo', 'session_key'), name='mensagem_unica_por_sessao')],
            },
        ),
    ]
