# Generated by Django 6.0.5 on 2026-05-14 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0008_perfilnkata_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('PERFIL_FALSO', 'Perfil falso'), ('FOTO_SUSPEITA', 'Foto suspeita'), ('COMPORTAMENTO_INADEQUADO', 'Comportamento inadequado'), ('DADOS_FALSOS', 'Dados falsos'), ('OUTRO', 'Outro motivo')], max_length=40)),
                ('detalhes', models.TextField(blank=True, help_text='Detalhes adicionais da denúncia.')),
                ('analisada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('denunciante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='entradas.perfilnkata')),
            ],
            options={
                'verbose_name': 'Denúncia de perfil',
                'verbose_name_plural': 'Denúncias de perfis',
                'ordering': ['-criado_em'],
            },
        ),
    ]
