# Generated by Django 6.0.5 on 2026-05-14 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0010_acaoperfil_usuario_mensagemperfil_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_origem', models.CharField(choices=[('INTERESSE', 'Interesse mútuo'), ('GOSTAR', 'Gosto mútuo')], default='INTERESSE', max_length=30)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_perfil_1', to='entradas.perfilnkata')),
                ('perfil_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_perfil_2', to='entradas.perfilnkata')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('perfil_1', 'perfil_2'), name='match_unico_entre_perfis')],
            },
        ),
    ]
