# Generated by Django 6.0.7 on 2026-08-20 18:48

import django.db.models.deletion
import django.utils.timezone
import entradas.identity_models
import entradas.storage_backends
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0016_register_prepared_feature_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoentrada',
            name='bi_frente',
            field=models.ImageField(blank=True, storage=entradas.storage_backends.identity_media_storage, upload_to='pedidos/documentos/'),
        ),
        migrations.AlterField(
            model_name='pedidoentrada',
            name='bi_verso',
            field=models.ImageField(blank=True, storage=entradas.storage_backends.identity_media_storage, upload_to='pedidos/documentos/'),
        ),
        migrations.AlterField(
            model_name='pedidoentrada',
            name='selfie_com_bi',
            field=models.ImageField(blank=True, storage=entradas.storage_backends.identity_media_storage, upload_to='pedidos/documentos/'),
        ),
        migrations.CreateModel(
            name='VerificacaoIdentidadeNKATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_hash', models.CharField(db_index=True, max_length=64)),
                ('idade_declarada', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('INICIADA', 'Iniciada'), ('EM_CAPTURA', 'Em captura'), ('A_ANALISAR', 'A analisar'), ('APROVADA', 'Aprovada automaticamente'), ('REVISAO', 'Revisão humana necessária'), ('REPETIR', 'Nova captura necessária'), ('REJEITADA', 'Rejeitada'), ('EXPIRADA', 'Expirada')], db_index=True, default='INICIADA', max_length=16)),
                ('risco', models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], db_index=True, default='INDEFINIDO', max_length=12)),
                ('pontuacao_risco', models.PositiveSmallIntegerField(default=0)),
                ('etapa_atual', models.CharField(default='bi_frente', max_length=24)),
                ('desafio_selfie', models.CharField(max_length=120)),
                ('aceita_biometria', models.BooleanField(default=False)),
                ('usar_foto_verificada', models.BooleanField(default=False)),
                ('bi_frente', models.ImageField(blank=True, storage=entradas.storage_backends.identity_media_storage, upload_to='nkata-id/documentos/%Y/%m/%d/')),
                ('bi_verso', models.ImageField(blank=True, storage=entradas.storage_backends.identity_media_storage, upload_to='nkata-id/documentos/%Y/%m/%d/')),
                ('selfie_ao_vivo', models.ImageField(blank=True, storage=entradas.storage_backends.identity_media_storage, upload_to='nkata-id/selfies/%Y/%m/%d/')),
                ('selfie_desafio', models.ImageField(blank=True, storage=entradas.storage_backends.identity_media_storage, upload_to='nkata-id/selfies/%Y/%m/%d/')),
                ('verificacoes_imagem', models.JSONField(blank=True, default=dict)),
                ('sinais_risco', models.JSONField(blank=True, default=dict)),
                ('documento_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('selfie_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provedor_biometrico', models.CharField(default='qualidade_local', max_length=40)),
                ('correspondencia_facial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vivacidade_confirmada', models.BooleanField(default=False)),
                ('decisao_origem', models.CharField(blank=True, choices=[('', 'Sem decisão'), ('AUTOMATICA', 'Automática'), ('HUMANA', 'Humana')], max_length=12)),
                ('nota_interna', models.TextField(blank=True)),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('consentido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_em', models.DateTimeField(db_index=True, default=entradas.identity_models.nkata_id_expires_at)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificacoes_nkata_id_analisadas', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificacao_identidade', to='entradas.pedidoentrada')),
            ],
            options={
                'verbose_name': 'Verificação NKATA ID',
                'verbose_name_plural': 'Verificações NKATA ID',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
