# Generated by Django 6.0.7 on 2026-08-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0017_nkata_id'),
        ('entradas', '0020_pushsubscriptionnkata'),
    ]

    operations = [
    ]
